server:
  port: 3000

spring:
  application:
    name:  myspringcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1083093341/myspirngcloud-config.git
        #uri: git@github.com:1083093341/myspirngcloud-config.git #GitHub上面的git仓库名字